# Generated by Django 4.2 on 2026-08-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
