# Generated by Django 4.2 on 2026-08-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.FileField(null=True, upload_to='site_them/'),
        ),
    ]
