# Generated by Django 4.2 on 2026-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_article_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.AddField(
            model_name='category',
            name='blogs',
            field=models.ManyToManyField(blank=True, to='app01.blog', verbose_name='所属站点'),
        ),
        migrations.AddField(
            model_name='tag',
            name='blogs',
            field=models.ManyToManyField(blank=True, to='app01.blog', verbose_name='所属站点'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.FileField(null=True, upload_to='site_theme/'),
        ),
    ]
