# Generated by Django 4.2 on 2026-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_remove_category_blog_remove_tag_blog_category_blogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='文章标题'),
        ),
    ]
