# Generated by Django 4.2 on 2026-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='爬取地址')),
                ('status', models.CharField(default='success', max_length=32, verbose_name='状态')),
                ('article_count', models.IntegerField(default=0, verbose_name='导入文章数')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='原创', max_length=32, verbose_name='文章来源'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='原文链接'),
        ),
    ]
